spring:
  application:
    name: auth-server
  profiles:
    default: default
  h2:
    console:
      enabled: false
  config:
    import: "optional:configserver:http://localhost:7777"
  datasource:
    username: sa
    url: jdbc:h2:mem:users;
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /auth-server
  port: 3030
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/