spring:
  application:
    name: report
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  cloud:
    stream:
      kafka:
        binder:
          broker: localhost:9092
      function:
        bindings:
          consumerReport-out-0:
            destination: consumerReport
server:
  servlet:
    context-path: /report-ms
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/